### ISSUE TITLE
Code logic explanation

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [Peyje/MAVeric#7]
Hi @Peyje, thanks for the great code base!

Could you explain the math / code behind your variables in MAV_QP.pdf and `trajectory_planner.py`?

I see you have the optimization equation 

![image](https://user-images.githubusercontent.com/33344633/122685354-a741d400-d1bf-11eb-82d4-747142febfbf.png)

but it doesn't seem to exactly match Minimum Snap Trajectory Generation and Control for Quadrotors's optimization equation in equation 11.

Also, could you explain where these equations come from? 

![image](https://user-images.githubusercontent.com/33344633/122685502-93e33880-d1c0-11eb-8172-20e18cdd56dc.png)

**Comment by Peyje** [comment]
Hi @kevin-thankyou-lin, thanks for the kind words!
Please take a look at the following PDF, therein I explained the origin of those equations. 
[optimization_problem.pdf](https://github.com/Peyje/MAVeric/files/6683024/optimization_problem.pdf)
I will close the issue for now, but feel free to continue asking questions if something is unclear.

**Comment by kevin-thankyou-lin** [comment]
Hi @Peyje, thanks for the prompt reply!

This PDF is exactly what I've been looking for - thank you for making and sharing it.

A few questions:

1. What is equation 4.4?
2. What is reference 22 referring to? "The complete code for all four coordinates can be found online [22]" (presumably it's this github repo?)
3. "As the problem at hand only contains squared terms, q can be set to zero". Would it be possible to specify the objective function for the 'problem at hand' that you're using? i.e. what's equation 4.3? 

Would it be possible to share the related chapters for this PDF? I think many of my questions would be resolved that way :) And, thanks for welcoming my questions!

**Comment by Peyje** [comment]
I forgot about the references in the PDF, sorry for that!
The equations 4.3 and 4.4 are the equations describing the actual minimization problem and therefore contain the fourth derivative of the position, the snap. You would be correct to assume that [22] is this very repo, yes.

The PDF excerpt is part of my Bachelor's thesis from a while back, if you wish to take a closer look at it just contact me at christopher[at]katins.me. Taking a look at how I came to define those equations might help you understand and work with this code.

**Comment by kevin-thankyou-lin** [comment]
No worries!

Gotcha, that makes sense to me. Just contacted you!
